server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: http://localhost:8089/
          predicates:
            Path=/api/v1/department/**
        - id: USER-SERVICE
          uri: http://localhost:8088/
          predicates:
            Path=/api/v1/users/**
